name: Build and Upload SumatraPDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y mingw-w64

    - name: Build SumatraPDF
      run: |
        export CC=x86_64-w64-mingw32-gcc
        export CXX=x86_64-w64-mingw32-g++
        ./build.sh

    - name: Upload SumatraPDF
      uses: actions/upload-artifact@v2
      with:
        name: SumatraPDF
        path: ./sumatrapdf.exe
